name: flutter_basis
description: Start point package for Flutter applications
version: 1.0.3+2
homepage:

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter:

dependencies:
  flutter:
    sdk: flutter
  get_it:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: